### ISSUE TITLE
Feature Request: use ImagicMagick through wand wrapper

### ISSUE THREAD

**Issue by xingren23** [jtydhr88/ComfyUI-ImageMagick#1]
Using Wand wrapper, images can be manipulated directly without the need to convert input and output to files, and there is no need to start a separate process.

**Comment by jtydhr88** [comment]
Hi, Thanks for feedback.
First, at beginning I considered using Python wrapper, such as wand.
However, after analyzed wand apis, I found out it would lost ImageMagick's flexiable, because it wrapped the image as an object and added methods into the object:
img.adaptive_blur(radius=8, sigma=4)
img.gaussian_blur(sigma=3)
img.motion_blur(radius=16, sigma=8, angle=-45)
etc.
If only implement a few features of image processing, wand is totally a great choose. 
However, it is not easy to coding here by using wand if I still want to keep "whole features" of ImageMagick.
So I choose currect solution, just run native magick directly in subprocess.

Anyway, thanks for your suggestion.

**Comment by jtydhr88** [comment]
https://github.com/Fannovel16/ComfyUI-MagickWand I think this what you are looking for.
